# Generated by Django 5.1.7 on 2025-09-09 10:21

import api.models.generate_ulid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(default=api.models.generate_ulid.generate_ulid, editable=False, max_length=26, unique=True)),
                ('status', models.CharField(choices=[('rescued', 'Rescued / Admitted'), ('quarantine', 'In Quarantine / Observation'), ('shelter', 'In Shelter'), ('foster', 'In Foster Care'), ('treatment', 'Under Veterinary Treatment'), ('rehabilitation', 'In Rehabilitation / Socialization'), ('reserved', 'Reserved'), ('adopted', 'Adopted'), ('returned', 'Returned'), ('transport', 'In Transit'), ('lost', 'Lost / Escaped'), ('deceased', 'Deceased'), ('euthanized', 'Euthanized')], default='rescued', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('chip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_id', models.CharField(default=api.models.generate_ulid.generate_ulid, editable=False, max_length=26, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(default=api.models.generate_ulid.generate_ulid, editable=False, max_length=26, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('USER', 'User')], default='USER', max_length=16)),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.shelter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
