# Generated by Django 5.2.6 on 2025-09-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
