# Generated by Django 5.2.6 on 2025-09-12 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shelter_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shelter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='email',
            field=models.EmailField(default='foo@shelter.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='shelter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['shelter_id'], name='api_shelter_shelter_43d58b_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['name'], name='api_shelter_name_4f8e76_idx'),
        ),
    ]
