# Generated by Django 5.2.6 on 2025-09-26 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shelter_options_shelter_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='api.shelter'),
            preserve_default=False,
        ),
    ]
