FROM nginx:latest

# COPY ./nginx.conf /etc/nginx/nginx.conf
# COPY ./default.conf /etc/nginx/conf.d/default.conf

# Fix ownership on startup, then start nginx
CMD ["sh", "-c", "chown -R nginx:nginx /usr/share/nginx/html && nginx -g 'daemon off;'"]
